### PR TITLE
Add Jest and some sample tests

### PR DESCRIPTION
**Pull request by n1313**
This PR adds Jest and some sample tests.

More specifically,

1. adds `jest` (main Jest package), `babel-jest` (its babel integration), `enzyme` (testing library), `enzyme-adapter-react-16` (its adapter to React 16) and `enzyme-to-json` (snapshot serialization helper) to devDependencies
1. adds `test:jest` and `test:coverage` scripts to package.json. Run `yarn test:jest` to run all Jest tests, run `yarn test:coverage` to run all Jest tests and calculate coverage, and run these scripts with `-u` key to automatically update snapshots
1. adds `@babel/preset-react` to .babelrc so that Jest can run on ES6 code
1. adds `jest: true` to .eslintrc so that Eslint doesn't complain about Jest globals in test files
1. adds `/coverage` folder to .gitignore to avoid committing test reports
1. adds jest.config.js configuration file (read more about configuring Jest: https://jestjs.io/docs/en/configuration.html). Jest is configured to look for test files in `test/jest` folder to avoid conflicts with existing Mocha tests in `test/unit`
1. adds `test/testSetup.js` file with Enzyme configuration
1. adds `test/fileMock.js` and `test/workerMock.js` files to mock out worker files and static files (e.g. SVGs, images, etc) in Jest snapshots
1. adds `test/jest/post-likes.test.js`, `test/jest/post-comments.test.js`, and `test/jest/piece-of-text.test.js` test files that do the same assertions as the existing component tests (for comparison of syntax)
1. adds new test file `test/jest/user-profile.test.js` with new tests for `<UserProfile>` component

Run `yarn test:coverage` to get an interactive test report generated in `coverage/lcov-report` folder.

See also https://freefeed.net/ffdev/0ebf369a-d793-4237-adf9-e3d99b67a525).

### CODE REVIEW

**Comment by n1313** [comment]
Travis build isn't starting for some reason :(

**Comment by n1313** [comment]
Will this PR be reviewed if I fix merge conflicts, or nobody cares?

**Comment by indeyets** [comment]
It waits for code stabilization (as snapshot tests are quite fragile in this regard). I'll review it after the next release

**Comment by n1313** [comment]
Надо все переделывать, возможно, без enzyme (потому что их, похоже, бросил airbnb, и до сих пор нет поддержки React 17). Этот пиар пусть пока повисит для референса, чтобы я мог подглядывать в ответы при работе над новым пиаром.

**Pull request closed without merging**
