### PR TITLE
Move bookmarklet into separate webpack-config

### PR DESCRIPTION
**Pull request by indeyets**
This way we can reliably isolate it from chunks-optimization.

### CODE REVIEW

**Comment by n1313** [comment]
What is the output location?

**Comment by indeyets** [comment]
`_dist/assets/js/bookmarklet-popup.js`

**Comment by n1313** [comment]
Would it be better if this location was defined in the config?

**Comment by indeyets** [comment]
Is there some use-case for that? :)

**Comment by n1313** [comment]
I think it is better to have variables and constants related to a single entity such as bookmarklet to be defined in as few files as possible (ideally, one). A build target being defined in that build's configuration file sounds logical to me.

**Comment by indeyets** [comment]
@n1313 I added second commit with this. It's a bit different that what you proposed, but it's the most simple code I managed to do this time. Alternative (with webpack injecting data via DefinePlugin) felt worse

**Comment by n1313** [comment]
As long as `output` is defined in bookmarklet config file, I'm happy. And great idea with defining a const to share the value between config and client code.

**Review by n1313 — APPROVED** [review]

**Pull request merged**
