### PR TITLE
Add links to some of sidebar block headers

### PR DESCRIPTION
**Pull request by n1313**
Click "My" to go to your account, click "Groups" to go to the list of all groups, click "FreeFeed" to go to @freefeed account

### CODE REVIEW

**Comment by dsumin** [comment]
Looks somewhat inconsistent, as My and Groups headers become links, while "Friend lists", "Bookmarklet" or "Memories of ..." are not.

**Comment by n1313** [comment]
Bookmarklet doesn't have a dedicated page that could be linked to (and I would argue that it doesn't deserve its space in the sidebar anyway). Memories -- same thing. Friend lists, yes. My bad, didn't think of it b/c I'm not using them.

**Comment by n1313** [comment]
@dsumin which page do you think should be linked to the "Friend lists" header?

**Comment by dsumin** [comment]
@n1313 I would suggest https://freefeed.net/friends

**Comment by n1313** [comment]
@dsumin done

**Review by dsumin — APPROVED** [review]
👍🏻

**Pull request merged**
