### PR TITLE
Added inline video playing for attached .mp4 and .webm videofiles

### PR DESCRIPTION
**Pull request by atarka**
I miss the opportunity to share short videofragments, since they are attached as links and are not easily viewable - most of the time i just have to convert them into gif, losing quality and gaining extra file size. This allows inline playing for two most popular web video formats. Like image collections video collections are foldable and sortable.

### CODE REVIEW

**Comment by davidmz** [comment]
I did that once in BetterFeed (v1). It was a bad decision: in some browsers the video played, in some (mostly iDevices) it did not.

I think video should always work in an official client. To do this, it must be converted to portable formats and codecs, via ffmpeg on our server or via [Amazon Elastic Transcoder](https://aws.amazon.com/ru/elastictranscoder/).

**Comment by atarka** [comment]
Maybe just disable videoplayer on devices with limited capability? Like on them Ipads? I believe modern browsers are really good at playing common formats, at least I haven't seen much problems playing any media in different browsers (although some encoded files are not seekable). I can even try to guess if the file can be played BEFORE i show the player - if the file is unplayable on this device i can just display it as a simple attachment, like it is now. 

I mean I don't think we'll have video transcoding anytime soon - it's not like you can do it in realtime when the video is being uploaded because of the process being quite slow and us not having any kind of processing queue (or do we have one?! =). Or maybe we can guess if video can be converted instantly (like, being 20 seconds or less) and process it if it's small enough, leaving longer videos untouched (uploading big videos should be discouraged anyways =)

**Comment by davidmz** [comment]
I'm still against it. Video is a complicated subject, there are a lot of nuances with containers, codecs, codec profiles... If we announce that we support video now, everyone will start loading video, but not everyone will be able to see it. That would make a very bad impression.

**Comment by davidmz** [comment]
(But my voice is not the deciding one)

**Pull request closed without merging**
