### PR TITLE
Attachments: display images and files

### PR DESCRIPTION
**Pull request by clbn**

### CODE REVIEW

**Comment by clbn** [comment]
@kadmil @ujenjt @berkus @indeyet
Don't hesitate to give me some :-1:s, I have very little experience with React so any feedback is really appreciated.

**Comment by indeyets** [comment]
why not to split into `GeneralAttachment` and `ImageAttachment` components?

**Comment by ujenjt** [comment]
Looks good :thumbsup:

**Comment by clbn** [comment]
@indeyets Do you mean creating `PostImageAttachment` in `post-image-attachment.jsx`, `PostGeneralAttachment` in `post-general-attachment.jsx` and so on? Sure, it's an option, current implementation just mimicks what we had in Ember. Let me know if you think it's better to split them this way.

Also, advice on naming (PostImageAttachment vs. PostAttachmentImage) would be appreciated.

**Comment by clbn** [comment]
@indeyets Done, thanks for the idea. Now there's no need to maintain separation condition (mediaType === 'image') in many places, I like it.

**Pull request merged**
